### ISSUE TITLE
fails in PHPStorm 2021.2.3

### ISSUE THREAD

**Issue by jfalch** [wisetime-io/intellij-branch-in-window-title#5]
Details: Current thread: Thread[GitRepositoryManager,4,main] 16431307
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1387178259

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:969)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.disableIndexUpToDateCheckInEdt(UniqueVFilePathBuilderImpl.java:182)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.lambda$getFilenameIndexModificationTracker$2(UniqueVFilePathBuilderImpl.java:126)
	at com.intellij.util.CachedValueBase.getTimeStamp(CachedValueBase.java:145)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:132)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:124)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:112)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:114)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.checkUpToDate(CachedValueBase.java:97)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:93)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:217)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:99)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePathWithinOpenedFileEditors(UniqueVFilePathBuilderImpl.java:52)
	at com.intellij.openapi.fileEditor.impl.UniqueNameEditorTabTitleProvider.getEditorTabTitle(UniqueNameEditorTabTitleProvider.java:28)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:22)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:21)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.lambda$getPresentableNameForUI$0(VfsPresentationUtil.java:29)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:146)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getPresentableNameForUI(VfsPresentationUtil.java:29)
	at com.intellij.openapi.wm.impl.PlatformFrameTitleBuilder.getFileTitle(PlatformFrameTitleBuilder.java:43)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.ClassTitlePane.updatePath(ClassTitlePane.kt:38)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.SelectedEditorFilePath.updatePath(SelectedEditorFilePath.kt:258)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.SelectedEditorFilePath.updateTitlePaths(SelectedEditorFilePath.kt:121)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.SelectedEditorFilePath.updateProjectPath(SelectedEditorFilePath.kt:63)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.titleLabel.CustomDecorationPath$titleChangeListener$1.propertyChange(CustomDecorationPath.kt:58)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:334)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8754)
	at java.desktop/java.awt.Frame.setTitle(Frame.java:526)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.doSetTitle(IdeFrameImpl.java:111)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.updateTitle(ProjectFrameHelper.java:310)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper$1.setTitle(ProjectFrameHelper.java:169)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.setTitle(IdeFrameImpl.java:106)
	at io.wisetime.idea.branch.BranchHelper.updateFrameTitle(BranchHelper.java:35)
	at io.wisetime.idea.branch.BranchHelper.onBranchChanged(BranchHelper.java:27)
	at io.wisetime.idea.branch.GitListener.notifyBranchChanged(GitListener.java:40)
	at io.wisetime.idea.branch.GitListener.lambda$runActivity$0(GitListener.java:23)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:386)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:172)
	at com.sun.proxy.$Proxy125.dirtyUnder(Unknown Source)
	at git4idea.annotate.GitRepositoryForAnnotationsListener$1.repositoryChanged(GitRepositoryForAnnotationsListener.java:18)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy123.repositoryChanged(Unknown Source)
	at git4idea.repo.GitRepositoryManager.lambda$notifyListenersAsync$2(GitRepositoryManager.java:90)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by sukolenvo** [comment]
Thanks for review and stacktrace. Fixed in v1.0.0. Please let me know if you experience any more issues.
